spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/table_name
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: DAVID
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jdbc:
    template:
     query-timeout: 90

  druid:
   stat-view-servlet:
    enabled: true
    login-username: admin
    login-password: 123456

   web-stat-filter:
    enabled: true
    urlPattern: /*
    exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
   aoppattern: com.atguigu.admin.*


# 配置mybatis規則
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 開啟matching駝峰命名規則
  configuration:    #指定mybatis全局配置文件中的相關配置項目
    map-underscore-to-camel-case: true
